# Generated by Django 5.2 on 2025-04-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Sarlavha')),
                ('button_name', models.CharField(max_length=32, verbose_name='Tugma nomi')),
                ('button_link', models.URLField(verbose_name='Tugma uchun manzil')),
                ('image', models.ImageField(upload_to='media/backgrounds', verbose_name='Orqa fon rasmi')),
            ],
            options={
                'verbose_name': 'Asosiy orqa fon',
                'verbose_name_plural': 'Asosiy orqa fonlar',
            },
        ),
    ]
