# Generated by Django 5.2 on 2025-04-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/about-us', verbose_name='Rasm')),
                ('title', models.CharField(max_length=64, verbose_name='Sarlavha')),
                ('more_info', models.TextField(verbose_name="Ko'proq ma'lumot")),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('title', models.CharField(max_length=16, verbose_name='Sarlavha')),
                ('more_info', models.CharField(max_length=64, verbose_name="Ko'proq ma'lumot")),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_about_features', to='main_app.homeaboutus')),
            ],
            options={
                'verbose_name': 'Biz haqimizda xizmat',
                'verbose_name_plural': 'Biz haqimizda xizmatlar',
            },
        ),
    ]
