# Generated by Django 5.2 on 2025-04-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_homeaboutus_homeaboutfeatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAboutFeatures',
        ),
    ]
