# Generated by Django 5.2 on 2025-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_homeservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeservices',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterField(
            model_name='homeservices',
            name='more_info',
            field=models.CharField(max_length=256, verbose_name="Ko'proq ma'lumot"),
        ),
    ]
