# Generated by Django 5.2 on 2025-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_homeservices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Sarlavha'),
        ),
    ]
