# Generated by Django 5.2 on 2025-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_homeservices_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Mahsulot')),
                ('text', models.TextField(verbose_name="Ko'proq ma'lumot")),
                ('image', models.ImageField(upload_to='media/products')),
            ],
        ),
    ]
