# Generated by Django 5.2 on 2025-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_products_options_products_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Xodimning ism, familiyasi')),
                ('position', models.CharField(max_length=64, verbose_name='Xodimning lavozimi')),
                ('image', models.ImageField(upload_to='media/employe', verbose_name='Xodimning rasmi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
