# Generated by Django 4.2 on 2025-05-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_homeaboutus_image_alter_homebackground_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaboutus',
            name='more_info_en',
            field=models.TextField(null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='homeaboutus',
            name='more_info_ru',
            field=models.TextField(null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='homeaboutus',
            name='more_info_uz',
            field=models.TextField(null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='homeaboutus',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homeaboutus',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homeaboutus',
            name='title_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='title_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='more_info_en',
            field=models.CharField(max_length=256, null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='more_info_ru',
            field=models.CharField(max_length=256, null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='more_info_uz',
            field=models.CharField(max_length=256, null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='title_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True, verbose_name="Yangilik haqida to'liq shu yerda yozing"),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True, verbose_name="Yangilik haqida to'liq shu yerda yozing"),
        ),
        migrations.AddField(
            model_name='news',
            name='text_uz',
            field=models.TextField(null=True, verbose_name="Yangilik haqida to'liq shu yerda yozing"),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='products',
            name='text_en',
            field=models.TextField(null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='products',
            name='text_ru',
            field=models.TextField(null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='products',
            name='text_uz',
            field=models.TextField(null=True, verbose_name="Ko'proq ma'lumot"),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Xodimning lavozimi'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Xodimning lavozimi'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Xodimning lavozimi'),
        ),
    ]
