# Generated by Django 4.2 on 2025-05-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_homeaboutus_more_info_en_homeaboutus_more_info_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebackground',
            name='button_name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='button_name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='homebackground',
            name='button_name_uz',
            field=models.CharField(max_length=32, null=True, verbose_name='Tugma nomi'),
        ),
    ]
