# Generated by Django 4.2 on 2025-05-26 04:26

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_wordarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordarticle',
            name='doc_file',
            field=models.FileField(upload_to=main_app.models.article_upload_to, verbose_name='Word hujjati (.docx)'),
        ),
    ]
