# Generated by Django 4.2 on 2025-05-26 09:54

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_wordarticle_doc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('html_file', models.FileField(upload_to=main_app.models.article_upload_to, verbose_name='HTML hujjat')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HTML maqola',
                'verbose_name_plural': 'HTML maqolalar',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='WordArticle',
        ),
    ]
